### ISSUE TITLE
Which network trained model are you using?

### ISSUE THREAD

**Issue by kingmacth** [SreekanthZipsy/mediapipe_car_detection#1]
Which network trained model are you using?

**Comment by SreekanthZipsy** [comment]
I have trained SSD_Mobilenet. I have used Tensorflow Object Detection API to train the model on Custom Cars dataset.

**Comment by kingmacth** [comment]
https://github.com/tensorflow/models/tree/238922e98dd0e8254b5c0921b241a1f5a151782f/research/object_detection/samples/configs

Which model is it?
